/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 model.gltf --transform 
Files: model.gltf [8.04KB] > C:\Users\valen\Documents\Developpement\portfolio\stories\Brainstorming\model-transformed.glb [2.44KB] (70%)
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/model-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.appleHalf.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload("/model-transformed.glb");
